fix up civet_release so it exits after a usage error,  add check to make sure argument is a path to a valid Civet log directory

diff --git a/bin/civet_release b/bin/civet_release
--- a/bin/civet_release
+++ b/bin/civet_release
@@ -2,14 +2,20 @@
 
 if [ $# -ne 1 ]; then
     echo "Usage: civet_release <log directory>" >&2
+    exit 1
 fi
 
 LOGDIR=$1
+
+if [[ ! -e $LOGDIR ]]; then
+    echo "Error:  \"${LOGDIR}\" does not appear to be a valid Civet log directory"  >&2
+    exit 2
+fi
     
 echo "releasing user hold on pipeline jobs"
     
 # just iterate over all of the job ids in this pipeline and try to 
-# qdel them.  We don't care what the state is, or even if they still exit
+# qrls them.  We don't care what the state is, or even if they still exit
 while read ID NAME DEP; do
     qrls $ID
 done < ${LOGDIR}/pipeline_batch_id_list.txt
